# Generated by Django 5.0.7 on 2024-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='todos',
            field=models.JSONField(default=list),
        ),
    ]
